server.port: 8081
server.error.include-message: always

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.academy.microservices.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG